### ISSUE TITLE
Toggle shrink is buggy

### ISSUE THREAD

**Issue by Nevrai** [gigabit101/Shrink#71]
Pressing the toggle shrink hotkey will either not shrink you, or it’ll shrink you, but you’ll glitch into blocks when walking around. Pressing it seems to frequently shrink you and then immediately unshrink you. The toggle shrink key seems to be broken, and you can only shrink properly by using the personal shrinking device.

I don’t know whether this is the same issue as #59, but I noticed that issue has been fixed in 1.3.4, which is not available for 1.18.2.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/) (version 0.4.27—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Shrink:** 1.3.3 (latest for 1.18.2)

**Comment by SpaceGentleman** [comment]
I don't know about the clipping into blocks thing, but I have also experienced the thing where it changes your size repeatedly while you hold the button, rather than changing it only once when you press the button. I don't know Minecraft modding, but asides from just fixing the issue, a good alternative to a keybind would be a clickable button in the size changer GUI. This mod would have been amazing for my server, if it were not for this one issue.
Minecraft 1.16.5
Forge 36.2.34
Shrink 1.1.6

Edit: Typo

**Comment by gigabit101** [comment]
I think I fixed the activation of the keybinding in 1.19+ I will check over the weekend and backport if needed

**Comment by Nevrai** [comment]
All right. I think that the toggle key would be super useful so you don’t have to switch to the personal shrinking device each time and don’t have to have it in your hotbar. I hope you can backport the fix to 1.18.2! Would be much appreciated.

**Comment by FlamesHYPERB** [comment]
how do I fix it when I shrink, my screen still shows in normal size 
Minecraft 1.18.2
forge 40.1.73
